version: 2
jobs:
  build:
    docker:
      - image: ifunky/polydev:latest
        environment:
          AWS_DEFAULT_REGION: eu-west-1 
    
    working_directory: ~/terraform
    steps:
      - checkout:
          path: ~/terraform
      - run:
          name: Validate
          command: make validate
      - run:
          name: Security Scan
          command: echo ID:${wiz_client_id};make wizscan wiz_client_id=${wiz_client_id} wiz_client_secret=${wiz_client_secret}